#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE auth_db;
    CREATE DATABASE cart_db;
    CREATE DATABASE profile_db;
    CREATE DATABASE order_db;
    CREATE DATABASE customer_support_db;
    CREATE DATABASE product_service_db;

    GRANT ALL PRIVILEGES ON DATABASE auth_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE cart_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE profile_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE order_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE customer_support_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE product_service_db TO $POSTGRES_USER;
EOSQL
