version: '3.8'

services:
  product-service:
    build: .
    container_name: product-service
    ports:
      - "5006:5006"
    volumes:
      - ./:/app
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DEBUG_MODE=True
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - shop-network

  db:
    image: postgres:13
    container_name: product-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=product_service
    ports:
      - "5435:5432"
    volumes:
      - product_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - shop-network

volumes:
  product_db_data:

networks:
  shop-network:
    external: true  # Use the existing network created by the main compose file
