version: '3.8'

services:
  profile-service:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://profile_user:profile_password@postgres:5432/profile_service_db
      - JWT_SECRET_KEY=your_super_secret_jwt_key
    depends_on:
      - postgres
    networks:
      - shop-network

  postgres:
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=profile_user
      - POSTGRES_PASSWORD=profile_password
      - POSTGRES_DB=profile_service_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shop-network

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres
    networks:
      - shop-network

volumes:
  postgres_data:

networks:
  shop-network:
    name: shop-network
    driver: bridge